### ISSUE TITLE
Better SEO

### ISSUE THREAD

**Issue by IoIxD** [IoIxD/dforum#2]
I or somebody needs to research how to do SEO stuff correctly so the posts are better able to be indexed.

**Comment by IoIxD** [comment]
#8

**Comment by samhza** [comment]
sitemap is pretty much all we need to get indexed and we have that now. closing

**Comment by IoIxD** [comment]
I disagree, there's a lot more we can do to improve SEO and this should remain open until we are more sure that we have better SEO.
The sitemap is not enough, to be a good service this needs to do a lot more for SEO.

**Comment by IoIxD** [comment]
I think we should research more and read Google's docs before just considering this done and closing the issue
https://developers.google.com/search/docs/

**Comment by IoIxD** [comment]
Google reports the number of "clicks and impressions" going up every time more pages are cached, leading me to the conclusion that I was wrong and this actually is good enough.
