### ISSUE TITLE
Discord-like CSS

### ISSUE THREAD

**Issue by IoIxD** [IoIxD/dforum#20]
The CSS should be redone to use the colors listed on [Discord's Branding Guide](https://discord.com/branding) and generally be closer to what Discord has right now.

**Comment by IoIxD** [comment]
Clarifying because I just got a screenshot of somebody working on a PR for this and it is a far cry from what I mean.

I think there should be more rounded corners and the colors should be changed. The layout is fine, and in fact I think Discord's UI does not lend itself to a forum at all. I think that this should generally look more like a traditional forum then a Discord chat.

**Comment by samhza** [comment]
addressed by 75904e7
