### ISSUE TITLE
Filter posts by tag in forum view

### ISSUE THREAD

**Issue by samhza** [IoIxD/dforum#61]

**Comment by lemonjesus** [comment]
It would be nice to have this feature that could dynamically filter tags on the front end, but I think it would also be a nice feature to hard-filter posts on the backend as well. For example, only render forum topics if they're tagged with a certain configurable tag.

I tried adding this myself but as of about a week ago the version of the Discord library used in DFS doesn't seem to support `appliedTags`. Maybe I'll take a crack at it again later.

**Comment by samhza** [comment]
The Discord library we use (arikawa) recently added support for AppliedTags and AvailableTags so it should be possible to implement now.

**Comment by IoIxD** [comment]
If we're gonna add this then it makes sense to add a search feature, (though, this would require the database mentioned in #12 o be added).

**Comment by samhza** [comment]
addressed by 75904e3b7bf843a795f30ed44cfe5bfca96b6c82
