### ISSUE TITLE
Wrong date shown on empty forums/posts.

### ISSUE THREAD

**Issue by IoIxD** [IoIxD/dforum#64]
![unknown-76.png](https://user-images.githubusercontent.com/30945097/195245942-3b20b8d4-6e19-4625-83aa-bfacdd6bffb0.png)

**Comment by IoIxD** [comment]
Fixed at an unknown date in an unknown commit.

**Comment by IoIxD** [comment]
nevermind

**Comment by IoIxD** [comment]
I found out why I got confused.
It only happens in production.

![image](https://user-images.githubusercontent.com/30945097/199593519-661758fd-9781-4f51-ae41-637fb8adcb42.png)
![image](https://user-images.githubusercontent.com/30945097/199593535-91ce8ad2-760d-4ae8-88e3-072e34f3b154.png)

**Comment by samhza** [comment]
addressed by 75904e3b7bf843a795f30ed44cfe5bfca96b6c82
