### ISSUE TITLE
add a favicon

### ISSUE THREAD

**Issue by IoIxD** [IoIxD/dforum#68]
we need a favicon

(not really but it's better then not having one at all imo)

**Comment by samhza** [comment]
![image](https://user-images.githubusercontent.com/31593190/197318041-81360d71-4744-497f-8d28-1bf438360444.png)
how's this

**Comment by IoIxD** [comment]
it's alright.

**Comment by samhza** [comment]
addressed by 75904e3b7bf843a795f30ed44cfe5bfca96b6c82
