### ISSUE TITLE
Anonymous Posting via Webhooks

### ISSUE THREAD

**Issue by Pieloaf** [IoIxD/dforum#80]
I'm not sure if Anonymous posting is not supported for security reasons or is seen as a technical limitation, but would it be possible to add anonymous posting via Discord webhooks? I remember seeing something done previously in a server where users could post under different names through a webhook? I haven't looked at the discord docs though to see if webhook bots can create/reply in forums? Just a thought. 
Maybe use a cookie to match a user to a post they made if they revisit the page on the same device like encoding the message id in the cookie? I've never worked with Go before but if it's something that you're open to I could take a look into it?

**Comment by samhza** [comment]
Anonymous posting would be a large target for abuse. Dforum's view into forums is read-only and we aren't planning to add any message sending features to it.

**Comment by Pieloaf** [comment]
Alright yeah, makes complete sense. Tbh I wouldn't have thought of it only for the fact it was explicitly stated as not supported so then I was curious was it for safety reasons or seen as a technical limitation 🙈
